; generated by PrusaSlicer 2.0.0+win64 on 2019-07-22 at 19:23:35

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M73 P0 R2
M73 Q0 S2
M201 X1000 Y1000 Z1000 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm/sec
M204 P1250 R1250 T1250 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E1.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107
M115 U3.7.1 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S215 ; set extruder temp
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M109 S215 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling
G1 Y-3.0 F1000.0 ; go outside print area
G92 E0.0
G1 X60.0 E9.0 F1000.0 ; intro line
M73 Q3 S2
M73 P3 R2
G1 X100.0 E12.5 F1000.0 ; intro line
G92 E0.0
M221 S95
M900 K30 ; Filament gcode
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2


G1 E-0.80000 F2100.00000
G1 Z0.600 F10800.000
;AFTER_LAYER_CHANGE
;0.2
G1 X110.118 Y91.546
G1 Z0.200
G1 E0.80000 F2100.00000
M204 S1000
G1 F1200
G1 X110.601 Y90.775 E0.02851
G1 X110.982 Y90.431 E0.01610
G1 X111.425 Y90.171 E0.01610
G1 X111.910 Y90.003 E0.01610
G1 X112.419 Y89.936 E0.01610
G1 X137.504 Y89.934 E0.78651
G1 X138.447 Y90.115 E0.03010
G1 X139.257 Y90.630 E0.03010
G1 X139.821 Y91.407 E0.03010
G1 X140.060 Y92.336 E0.03010
G1 X140.065 Y117.563 E0.79098
G1 X139.882 Y118.454 E0.02851
G1 X139.399 Y119.225 E0.02851
G1 X139.005 Y119.578 E0.01660
G1 X138.547 Y119.842 E0.01660
G1 X138.044 Y120.007 E0.01660
G1 X137.517 Y120.066 E0.01660
G1 X112.437 Y120.065 E0.78639
G1 X111.546 Y119.882 E0.02851
G1 X110.775 Y119.399 E0.02851
G1 X110.422 Y119.005 E0.01660
G1 X110.158 Y118.547 E0.01660
G1 X109.993 Y118.044 E0.01660
G1 X109.934 Y117.517 E0.01660
G1 X109.935 Y92.437 E0.78639
G1 X110.106 Y91.605 E0.02663
G1 F8640
G1 X110.601 Y90.775 E-0.22299
G1 X110.982 Y90.431 E-0.11858
G1 X111.425 Y90.171 E-0.11859
G1 X111.910 Y90.003 E-0.11859
G1 X112.419 Y89.936 E-0.11859
G1 X112.691 Y89.936 E-0.06267
G1 E-0.04000 F2100.00000
G1 Z0.800 F10800.000
G1 X111.594 Y90.508
G1 Z0.200
G1 E0.80000 F2100.00000
G1 F1200
G1 X112.443 Y90.312 E0.02732
G1 X137.504 Y90.311 E0.78576
G1 X138.313 Y90.468 E0.02586
G1 X139.005 Y90.911 E0.02574
G1 X139.486 Y91.581 E0.02586
G1 X139.685 Y92.377 E0.02574
G1 X139.688 Y117.548 E0.78920
G1 X139.530 Y118.317 E0.02462
G1 X139.112 Y118.981 E0.02462
G1 X138.383 Y119.503 E0.02810
G1 X137.510 Y119.689 E0.02799
G1 X112.452 Y119.688 E0.78565
G1 X111.683 Y119.530 E0.02462
G1 X111.019 Y119.112 E0.02462
G1 X110.497 Y118.383 E0.02810
G1 X110.311 Y117.510 E0.02799
G1 X110.312 Y92.452 E0.78565
G1 X110.470 Y91.683 E0.02462
G1 X110.888 Y91.019 E0.02462
G1 X111.545 Y90.543 E0.02544
G1 F8640
G1 X112.443 Y90.312 E-0.21401
G1 X114.808 Y90.312 E-0.54599
G1 E-0.04000 F2100.00000
G1 Z0.800 F10800.000
G1 X113.087 Y93.087
G1 Z0.200
G1 E0.80000 F2100.00000
G1 F1200
G1 X113.413 Y93.087 E0.01022
G1 X113.413 Y95.587 E0.07839
G1 X136.913 Y95.587 E0.73683
G1 X136.913 Y98.913 E0.10428
G1 X113.413 Y98.913 E0.73683
G1 X113.413 Y101.587 E0.08385
G1 X136.913 Y101.587 E0.73683
G1 X136.913 Y104.913 E0.10428
G1 X113.413 Y104.913 E0.73683
G1 X113.413 Y107.587 E0.08385
G1 X136.913 Y107.587 E0.73683
G1 X136.913 Y110.913 E0.10428
G1 X113.413 Y110.913 E0.73683
G1 X113.413 Y113.587 E0.08385
G1 X136.913 Y113.587 E0.73683
G1 X136.913 Y116.913 E0.10428
G1 X113.087 Y116.913 E0.74704
G1 X113.087 Y116.587 E0.01022
G1 X136.587 Y116.587 E0.73683
G1 X136.587 Y113.913 E0.08385
G1 X113.087 Y113.913 E0.73683
G1 X113.087 Y110.587 E0.10428
G1 X136.587 Y110.587 E0.73683
G1 X136.587 Y107.913 E0.08385
G1 X113.087 Y107.913 E0.73683
G1 X113.087 Y104.587 E0.10428
G1 X136.587 Y104.587 E0.73683
G1 X136.587 Y101.913 E0.08385
G1 X113.087 Y101.913 E0.73683
G1 X113.087 Y98.587 E0.10428
G1 X136.587 Y98.587 E0.73683
G1 X136.587 Y95.913 E0.08385
G1 X113.087 Y95.913 E0.73683
G1 X113.087 Y93.147 E0.08672
G1 X113.790 Y93.290 F10800.000
G1 F1200
G1 X113.790 Y95.210 E0.06020
G1 X137.290 Y95.210 E0.73683
G1 X137.290 Y99.290 E0.12793
G1 X113.790 Y99.290 E0.73683
G1 X113.790 Y101.210 E0.06020
G1 X137.290 Y101.210 E0.73683
G1 X137.290 Y105.290 E0.12793
G1 X113.790 Y105.290 E0.73683
G1 X113.790 Y107.210 E0.06020
G1 X137.290 Y107.210 E0.73683
G1 X137.290 Y111.290 E0.12793
G1 X113.790 Y111.290 E0.73683
G1 X113.790 Y113.210 E0.06020
G1 X137.290 Y113.210 E0.73683
G1 X137.290 Y117.290 E0.12793
G1 X112.710 Y117.290 E0.77069
G1 X112.710 Y116.210 E0.03386
G1 X136.210 Y116.210 E0.73683
G1 X136.210 Y114.290 E0.06020
G1 X112.710 Y114.290 E0.73683
G1 X112.710 Y110.210 E0.12793
G1 X136.210 Y110.210 E0.73683
G1 X136.210 Y108.290 E0.06020
G1 X112.710 Y108.290 E0.73683
G1 X112.710 Y104.210 E0.12793
G1 X136.210 Y104.210 E0.73683
G1 X136.210 Y102.290 E0.06020
G1 X112.710 Y102.290 E0.73683
G1 X112.710 Y98.210 E0.12793
G1 X136.210 Y98.210 E0.73683
G1 X136.210 Y96.290 E0.06020
G1 X112.710 Y96.290 E0.73683
G1 X112.710 Y92.710 E0.11225
G1 X137.290 Y92.710 E0.77069
M73 Q63 S1
G1 X137.290 Y93.290 E0.01819
G1 X113.850 Y93.290 E0.73494
M73 P64 R1
G1 X113.390 Y93.293 F10800.000
G1 X113.601 Y93.000
G1 F1200
G1 X137.101 Y93.000 E0.39652
M106 S255
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.4


G1 F8640
G1 X133.810 Y93.000 E-0.76000
G1 E-0.04000 F2100.00000
G1 Z0.800 F10800.000
;AFTER_LAYER_CHANGE
;0.4
G1 X138.447 Y90.115
G1 Z0.400
G1 E0.80000 F2100.00000
G1 F3000
G1 X139.257 Y90.630 E0.03010
G1 X139.821 Y91.407 E0.03010
G1 X140.060 Y92.336 E0.03010
G1 X140.065 Y117.563 E0.79098
G1 X139.882 Y118.454 E0.02851
G1 X139.399 Y119.225 E0.02851
G1 X139.005 Y119.578 E0.01660
G1 X138.547 Y119.842 E0.01660
G1 X138.044 Y120.007 E0.01660
G1 X137.517 Y120.066 E0.01660
G1 X112.437 Y120.065 E0.78639
G1 X111.546 Y119.882 E0.02851
G1 X110.775 Y119.399 E0.02851
G1 X110.422 Y119.005 E0.01660
G1 X110.158 Y118.547 E0.01660
G1 X109.993 Y118.044 E0.01660
G1 X109.934 Y117.517 E0.01660
G1 X109.935 Y92.437 E0.78639
G1 X110.118 Y91.546 E0.02851
G1 X110.601 Y90.775 E0.02851
G1 X110.982 Y90.431 E0.01610
G1 X111.425 Y90.171 E0.01610
G1 X111.910 Y90.003 E0.01610
G1 X112.419 Y89.936 E0.01610
G1 X137.504 Y89.934 E0.78651
G1 X138.388 Y90.104 E0.02821
G1 F8640
G1 X139.257 Y90.630 E-0.23458
G1 X139.821 Y91.407 E-0.22164
G1 X140.060 Y92.336 E-0.22164
G1 X140.060 Y92.692 E-0.08215
G1 E-0.04000 F2100.00000
G1 Z1.000 F10800.000
G1 X136.868 Y95.632
G1 Z0.400
G1 E0.80000 F2100.00000
M204 S800
G1 F3600
G1 X136.868 Y98.868 E0.10953
G1 X113.368 Y98.868 E0.79545
G1 X113.368 Y101.632 E0.09356
G1 X136.868 Y101.632 E0.79545
G1 X136.868 Y104.868 E0.10953
G1 X113.368 Y104.868 E0.79545
G1 X113.368 Y107.632 E0.09356
G1 X136.868 Y107.632 E0.79545
G1 X136.868 Y110.868 E0.10953
G1 X113.368 Y110.868 E0.79545
G1 X113.368 Y113.632 E0.09356
G1 X136.868 Y113.632 E0.79545
G1 X136.868 Y116.868 E0.10953
G1 X113.132 Y116.868 E0.80343
G1 X113.132 Y116.632 E0.00798
G1 X136.632 Y116.632 E0.79545
G1 X136.632 Y113.868 E0.09356
G1 X113.132 Y113.868 E0.79545
G1 X113.132 Y110.632 E0.10953
G1 X136.632 Y110.632 E0.79545
G1 X136.632 Y107.868 E0.09356
G1 X113.132 Y107.868 E0.79545
G1 X113.132 Y104.632 E0.10953
G1 X136.632 Y104.632 E0.79545
G1 X136.632 Y101.868 E0.09356
G1 X113.132 Y101.868 E0.79545
G1 X113.132 Y98.632 E0.10953
G1 X136.632 Y98.632 E0.79545
G1 X136.632 Y95.868 E0.09356
G1 X113.132 Y95.868 E0.79545
G1 X113.132 Y93.132 E0.09261
G1 X113.368 Y93.132 E0.00798
G1 X113.368 Y95.632 E0.08462
G1 X136.808 Y95.632 E0.79342
M204 S1000
G1 F8640
G1 X136.868 Y98.868 E-0.74729
G1 X136.813 Y98.868 E-0.01271
G1 E-0.04000 F2100.00000
G1 Z1.000 F10800.000
G1 X113.775 Y93.275
G1 Z0.400
G1 E0.80000 F2100.00000
M204 S800
G1 X113.775 Y95.225 E0.06601
G1 X137.275 Y95.225 E0.79545
G1 X137.275 Y99.275 E0.13709
G1 X113.775 Y99.275 E0.79545
G1 X113.775 Y101.225 E0.06601
G1 X137.275 Y101.225 E0.79545
G1 X137.275 Y105.275 E0.13709
G1 X113.775 Y105.275 E0.79545
G1 X113.775 Y107.225 E0.06601
G1 X137.275 Y107.225 E0.79545
G1 X137.275 Y111.275 E0.13709
G1 X113.775 Y111.275 E0.79545
G1 X113.775 Y113.225 E0.06601
G1 X137.275 Y113.225 E0.79545
G1 X137.275 Y117.275 E0.13709
G1 X112.725 Y117.275 E0.83099
G1 X112.725 Y116.225 E0.03554
G1 X136.225 Y116.225 E0.79545
G1 X136.225 Y114.275 E0.06601
G1 X112.725 Y114.275 E0.79545
G1 X112.725 Y110.225 E0.13709
G1 X136.225 Y110.225 E0.79545
G1 X136.225 Y108.275 E0.06601
G1 X112.725 Y108.275 E0.79545
G1 X112.725 Y104.225 E0.13709
G1 X136.225 Y104.225 E0.79545
G1 X136.225 Y102.275 E0.06601
G1 X112.725 Y102.275 E0.79545
G1 X112.725 Y98.225 E0.13709
G1 X136.225 Y98.225 E0.79545
G1 X136.225 Y96.275 E0.06601
G1 X112.725 Y96.275 E0.79545
G1 X112.725 Y92.725 E0.12016
G1 X137.275 Y92.725 E0.83099
G1 X137.275 Y93.275 E0.01862
G1 X113.835 Y93.275 E0.79342
M204 S1000
G1 X113.375 Y93.278 F10800.000
G1 X113.571 Y93.000
G1 F2400
G1 X137.071 Y93.000 E0.27928
G1 F8640;_WIPE
G1 X133.780 Y93.000 E-0.76000
G1 E-0.04000 F2100.00000
G1 Z1.000 F10800.000
M107
; Filament-specific end gcode
G4 ; wait
M221 S100
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
G1 Z31 ; Move print head up
G1 X0 Y200 F3000 ; home X axis
M84 ; disable motors
M73 P100 R0
M73 Q100 S0
; filament used [mm] = 70.1
; filament used [cm3] = 0.2
; filament used [g] = 0.2
; filament cost = 0.0
; total filament used [g] = 0.2
; total filament cost = 0.0
; estimated printing time (normal mode) = 1m 40s
; estimated printing time (silent mode) = 1m 40s

; avoid_crossing_perimeters = 0
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bridge_acceleration = 1000
; bridge_fan_speed = 100
; brim_width = 0
; colorprint_heights = 
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; deretract_speed = 0
; disable_fan_first_layers = 1
; duplicate_distance = 6
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = G4 ; wait\nM221 S100\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\n{if layer_z < max_print_height}G1 Z{z_offset+min(layer_z+30, max_print_height)}{endif} ; Move print head up\nG1 X0 Y200 F3000 ; home X axis\nM84 ; disable motors
; extra_loading_move = -2
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = #FFFF00
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FF3232
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 24.99
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = "Affordable filament for everyday printing in premium quality manufactured in-house by Josef Prusa"
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_soluble = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; first_layer_acceleration = 1000
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_speed = 20
; first_layer_temperature = 215
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 0
; high_current_on_filament_swap = 0
; infill_acceleration = 1250
; infill_first = 0
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 1000,1000
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 1.5,1.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 200
; max_volumetric_speed = 0
; min_fan_speed = 100
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}_{printer_model}.gcode
; parking_pos_retraction = 92
; perimeter_acceleration = 800
; post_process = 
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 4
; retract_lift = 0.6
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slowdown_below_layer_time = 20
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}200{elsif nozzle_diameter[0]==0.6}18{else}30{endif} ; Filament gcode"
; start_gcode = M115 U3.7.1 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\nG1 Y-3.0 F1000.0 ; go outside print area\nG92 E0.0\nG1 X60.0 E9.0 F1000.0 ; intro line\nG1 X100.0 E12.5 F1000.0 ; intro line\nG92 E0.0\nM221 S{if layer_height<0.075}100{else}95{endif}
; temperature = 215
; threads = 8
; toolchange_gcode = 
; travel_speed = 180
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 1
; wipe_tower = 1
; wipe_tower_bridging = 10
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; z_offset = 0
; clip_multipart_objects = 1
; dont_support_bridges = 1
; elefant_foot_compensation = 0
; extrusion_width = 0.45
; first_layer_height = 0.2
; infill_only_where_needed = 0
; interface_shells = 0
; layer_height = 0.2
; raft_layers = 0
; seam_position = nearest
; slice_closing_radius = 0.049
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_buildplate_only = 1
; support_material_contact_distance = 0.1
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_synchronize_layers = 0
; support_material_threshold = 55
; support_material_with_sheath = 0
; support_material_xy_spacing = 50%
; wipe_into_objects = 0
; xy_size_compensation = 0
; bottom_fill_pattern = rectilinear
; bottom_solid_layers = 4
; bridge_angle = 0
; bridge_flow_ratio = 0.95
; bridge_speed = 30
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 35
; external_perimeters_first = 0
; extra_perimeters = 0
; fill_angle = 45
; fill_density = 15%
; fill_pattern = honeycomb
; gap_fill_speed = 40
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_overlap = 25%
; infill_speed = 200
; overhangs = 1
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_speed = 60
; perimeters = 2
; small_perimeter_speed = 25
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 200
; thin_walls = 0
; top_fill_pattern = rectilinear
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 50
; top_solid_layers = 5
; wipe_into_infill = 0
; print_settings_id = 0.20mm SPEED MK3 (honeycomb)
; filament_settings_id = "Prusament PLA"
; printer_settings_id = Original Prusa i3 MK3S
; printer_model = MK3S
; printer_variant = 0.4
; default_print_profile = 0.15mm QUALITY MK3
; default_filament_profile = "Prusament PLA"
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK3.*/ and nozzle_diameter[0]==0.4";"! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; inherits_cummulative = "0.20mm SPEED MK3";;
